README.md

Though I'm not really sure if Rebound fits into "Animations" category.

Added the Rebound library

---

README.md

I used this decompiler last week on an Android jar library and it worked well.

Add procyon decompiler

---

README.md

Added Trail library under the Utility section.

Add: Trail by @mauriciotogneri

---

README.md

https://github.com/percolate/caffeine

Added Percolate's Caffeine Library 

---

README.md

I added [Decor](https://github.com/chemouna/decor) library

Add Decor library

---

README.md

Removed one reference to https://github.com/antoniolg/androidmvp and left the one with more detailed description.

Removed duplicate androidmvp entry

---

README.md

Added a link to the nucleus MVP library and a port of the u2020 app using MVP and Dagger 2

Added MVP samples

---

README.md

Included Teleport library - Data Sync & Messaging Library for Android Wear

Added Teleport library

---

README.md

[https://github.com/badoo/android-weak-handler](https://github.com/badoo/android-weak-handler)

ADD WeakHandler to others

---

README.md

Signed-off-by: Diogo Rosa <diogo.m.c.rosa@gmail.com>

Add Liquid analytics to SDKs

---

README.md

1. **Banjen** Open source brazilian banjo tunner, example to play local sounds.
[https://github.com/MakinGiants/android_banjo_tuner](https://github.com/MakinGiants/android_banjo_tuner)
1. **LiveView Funny** LiveView app that play sounds in the phone from the watch.
[https://github.com/MakinGiants/LiveView-Funny-Plugin](https://github.com/MakinGiants/LiveView-Funny-Plugin)
1. **LiveView Answer-it** LiveView app that send sms to call history contacts.
[https://github.com/MakinGiants/LiveView-Answer-it](https://github.com/MakinGiants/LiveView-Answer-it)
1. **LiveView Tell-it** LiveView app that send default sms to favorite contacts.
[https://github.com/MakinGiants/LiveView-Tell-it](https://github.com/MakinGiants/LiveView-Tell-it)

Add MakinGiants opensource apps to App

---

README.md

add MaterialLoadingProgressBar

add MaterialLoadingProgressBar

---

README.md

aSmack is deprecated, you can now use Smack directly on Android.

Replace aSmack with Smack

---

README.md

Add node-android networking stack

Add node-android networking stack

---

README.md

Piclice is FOSS Android application to slice and share pictures

Add Piclice to the App category

---

README.md

Material design ProgressBar with consistent appearance on Android 4.0+

Add MaterialProgressBar

---

README.md

DiscreteSeekBar library was listed twice.

Remove DiscreteSeekBar extra link

---

README.md

add leakcanary, goreinu

---

README.md

Android library that provides multiple image selection (https://github.com/darsh2/MultipleImageSelect)

Add MultipleImageSelect

---

README.md

Added one of my own recently created Library to the list.

Add SeekBarCompat

---

README.md

My material animation library.

Added CircularTools

---

README.md

I would like to add Percolate's Foam Library (https://github.com/percolate/foam) under ```Utility```.

Added Percolate's Foam Library

---

README.md

Barcode library added

---

README.md

Added TextSurface in TextView/EditText category : A little animation framework which could help you to show message in a nice looking way.

Added TextSurface

---

README.md

Added FontBinding and Lobsterpicker

Added FontBinding and Lobsterpicker

---

README.md

add loading progress

---

README.md

Added RxRecyclerAdapter library to the Adapters section.

Add RxRecyclerAdapter 

---

README.md

Annotation based simple API flavoured with AOP to handle new Android runtime permission model

Added canelmas's "let" library

---

README.md

add a reading app Leisure to repo

---

README.md

* Added Ok2Curl library to Utility list

Added Ok2Curl to Utility list

---

README.md

`Game` category was created and `Space in Charge` was appended to.

Add "Space in Charge" to "Game" category

---

README.md

Add DroidLane: Deployment plugin to upload apk to Google Play.

Add DroidLane plugin

---

README.md

Could you include our latest library we built at Coshx Labs?
Thanks!

Adds Drekkar to Buses

---

README.md

added DilatingDotsProgressBar

---

README.md

Added Entry Screens

---

README.md

Market : http://coolapk.com/apk/com.tneciv.zhihudaily

add a material design android app with MVP

---

README.md

This is a customizable circular progressbar.It can achieve the effect of the QQ health's arc progress with XML. What's more, we can use it by only a few codes to do the beautiful and colorful dashboard to show current data.

add ColorArcProgressBar

---

README.md

Hi,
I would like to add my library!
Thanks

add ipcam-view library

---

README.md

I have added my library to the readme! Hope you can merge it! :+1:

Added material-calendar-view to readme.md

---

README.md

add awesome-campus to App

---

README.md

Android Networking is a powerful library for doing any type of networking in Android applications.

New Library added in Network

---

README.md

Added KerningViews and PinLockView library

Updated README with new libraries

---

README.md

Add SectionedRecyclerViewAdapter library under Adapter category.

Add SectionedRecyclerViewAdapter library

---

README.md

Glide Bitmap Pool is added in Image Loading category

New Library added in Image Loading

---

Widget.md

[EasyIntro](https://github.com/meNESS/EasyIntro) is the flexible, easy to use, all in one app intro library for Android.

EasyIntro library added to Activity section

---

Widget.md

[TargetView](https://github.com/anastr/SimpleTargetView) : 
[SpeedView](https://github.com/anastr/SpeedView) :

add SpeedView, TargetView by @anastr

---

Widget.md

A custom view with keyboard and character display to be used for authentication.

added passcodeview library

---

Widget.md

add AwesomeProgressbar and TumblrLikeAnimView

add AwesomeProgressbar and TumblrLikeAnimView

---

Component.md

Update : Add oAuthLibGithub Library

---

Other.md

Added DroidAwesome Android Library
https://github.com/Livin21/DroidAwesome

Add: DroidAwesome

---

Widget.md

https://github.com/tekinarslan/AndroidMaterialDesignToolbar

Add memo project not supported

---

Common.md

Add Android Upload service library. https://github.com/gotev/android-upload-service

Add: android upload service

---

Other.md

add lib : https://github.com/lfkdsk/JustWeEngine

Add: JustWeEngine By: lfkdsk

---

Common.md
Widget.md

https://github.com/mirrajabi/okhttp-json-mock
https://github.com/mirrajabi/ViewEffects

Adds vieweffect and okhttp-json-mock

---

Widget.md

https://github.com/luongvo/iOS-SwitchView

Added iOS-SwitchView - A lightweight iOS switch view style for Android

---

Other.md

Fakeit generates realistic fake data — like names, emails, dates, countries — to be used in your Android development environment.
[https://github.com/moove-it/fakeit](https://github.com/moove-it/fakeit)

[Tools] Add Fakeit library

---

README.md

Hi, I have a maintained awesome-android repository and it would be great, if you could link to that as well. Thanks!

Added link to maintained awesome-android
